SELECT B.RANDOM_VALUE
    	,A.*
FROM
(
SELECT 1 AS USER_ID, 'User 1' AS USER_NAME FROM DUAL UNION ALL
SELECT 2 AS USER_ID, 'User 2' AS USER_NAME FROM DUAL UNION ALL
SELECT 3 AS USER_ID, 'User 3' AS USER_NAME FROM DUAL UNION ALL
SELECT 4 AS USER_ID, 'User 4' AS USER_NAME FROM DUAL UNION ALL
SELECT 5 AS USER_ID, 'User 5' AS USER_NAME FROM DUAL UNION ALL
SELECT 6 AS USER_ID, 'User 6' AS USER_NAME FROM DUAL UNION ALL
SELECT 7 AS USER_ID, 'User 7' AS USER_NAME FROM DUAL UNION ALL
SELECT 8 AS USER_ID, 'User 8' AS USER_NAME FROM DUAL UNION ALL
SELECT 9 AS USER_ID, 'User 9' AS USER_NAME FROM DUAL UNION ALL
SELECT 10 AS USER_ID, 'User 10' AS USER_NAME FROM DUAL
) A

INNER JOIN

(
SELECT TRUNC(DBMS_RANDOM.VALUE(1,10)) AS RANDOM_VALUE FROM DUAL
) B
ON A.USER_ID = B.RANDOM_VALUE
;
