-- FINDING LAST THURSDAY (OR ANY DAY) BEFORE END OF NEXT MONTH (END OF MONTH IS EXCLUDED)
SELECT TEST_DATE AS START_DATE
        ,CASE WHEN TO_CHAR(LAST_DAY(ADD_MONTHS(TEST_DATE,1)) - 7 ,'D') = 5 THEN LAST_DAY(ADD_MONTHS(TEST_DATE,1)) - 7  -- IT CHECKS IF THE DAY IS THURSDAY. (STARTING TO COUNT FROM SUNDAY).
        -- IF IT IS THURSDAY THAT MEANS IT IS THE LAST THURSDAY BEFORE END OF MONTH
              ELSE NEXT_DAY(LAST_DAY(ADD_MONTHS(TEST_DATE,1)) - 7 ,'THURSDAY') -- NEXT THURSDAY STILL WOULD BE LAST THURSDAY BEFORE END OF MONTH
      END AS NEXT_THURSDAY_V1
     
      ,CASE WHEN TO_CHAR(LAST_DAY(ADD_MONTHS(TEST_DATE,1)) ,'D') = 5 THEN LAST_DAY(ADD_MONTHS(TEST_DATE,1)) -- CHECKING IF THE LAST DAY OF THE NEXT MONTH IS THURSDAY
            WHEN TO_CHAR(LAST_DAY(ADD_MONTHS(TEST_DATE,1)) - 7 ,'D') = 5 THEN LAST_DAY(ADD_MONTHS(TEST_DATE,1)) - 7 -- SAME AS BEFORE
            ELSE NEXT_DAY(LAST_DAY(ADD_MONTHS(TEST_DATE,1)) - 7 ,'THURSDAY') -- SAME AS BEFORE
      END AS NEXT_THURSDAY_V2 -- IF END OF MONTH IS INCLUDED
FROM
    (
    SELECT TO_DATE('25082021' ,'DDMMYYYY') AS TEST_DATE
    FROM DUAL
    )
;
